### ISSUE TITLE
WRONG DETECTION

### ISSUE THREAD

**Issue by zaimodz** [Pete9xi/Paradox_AntiCheat#31]
THE BUG IS SO ANNOYING, Especially when there's no admin around, you'll just get killed by mobs and you're stuff loses.

1. Antikillaura
2. Antiscaffold 
3. Idk if there's more

IDK why it happens even you didn't use scaffolding ( idk what's antiscaffold do )

I have several screenshots of my members saying they get freeze by paradox

DOES THE SPAWN PROTECTION WORKS??

**Comment by Visual1mpact** [comment]
Be sure it is a bug or if your player base is crying because they were caught. Seen too many people claim bugs but it wasn't the case. This isn't to dismiss if there is actually a bug lingering, but you need to provide evidence @zaimodz . Never take their word for it. Investigate and determine if their claims are valid or if they are hiding the truth.
